name: k8s-playground

services:
  k3s:
    image: rancher/k3s:v1.35.8-k3s1
    container_name: k3s
    privileged: true
    restart: unless-stopped

    command:
      - "server"
      # Cilium docs suggest setting `none` to the CNI when using cilium with headlamp
      # curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='--flannel-backend=none
      # Cilium can replace kube-proxy, that why we are not using `--disable-kube-proxy` yet.
      - "--flannel-backend=none"
      # Disable K3s built-in network policy controller; Cilium will handle policies.
      - "--disable-network-policy"
      - "--disable=traefik"
      - "--disable=servicelb"
      - "--write-kubeconfig=/output/kubeconfig.yaml"
      - "--write-kubeconfig-mode=644"

    ports:
      - "6443:6443"

    volumes:
      - k3s-data:/var/lib/rancher/k3s
      - ./.kube:/output

    tmpfs:
      - /run
      - /var/run

  tools:
    build:
      context: ./tools

    container_name: k8s-tools

    network_mode: "service:k3s"

    depends_on:
      - k3s

    environment:
      KUBECONFIG: /root/.kube/kubeconfig.yaml

    volumes:
      - ./.kube:/root/.kube:ro
      - ./cilium:/workspace/cilium:ro

volumes:
  k3s-data: